/**
 * Rewrites the static prerender inside `index.html` from the app's own data.
 *
 * The block between the PRERENDER markers is what crawlers and social bots
 * read: React replaces it on mount, so no visitor ever sees it, which is
 * exactly why it rotted unnoticed. By the time anyone looked it disagreed with
 * the app in four places — it advertised 10 coding challenges against the
 * app's 40, pointed the first cybersecurity lecture at a dead gamma.app URL,
 * numbered that track's lectures from an order that had since changed, and
 * listed hero buttons that had been renamed.
 *
 * Hand-maintained duplicate copy drifts. Generated copy cannot, so this reads
 * the same modules the components render from.
 *
 * Run with `pnpm run generate-prerender`, and re-run it whenever the lecture
 * list, the challenge set or the section order changes.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { en } from '../src/lib/locales/en';
import { EN as LECTURES } from '../src/lib/lectures';
import { EN_BANK } from '../src/lib/questionBank';
import { SECTIONS } from '../src/lib/sections';

const here = path.dirname(fileURLToPath(import.meta.url));
const indexPath = path.resolve(here, '..', 'index.html');

const START = '<!-- PRERENDER:START -->';
const END = '<!-- PRERENDER:END -->';

/** HTML-escapes text coming from the locale modules. */
function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Strips the leading emoji from a nav label — it is decoration, not content. */
function plain(label: string): string {
  return label.replace(/^[^\p{L}\p{N}]+/u, '').trim();
}

const navLinks = SECTIONS.map(
  section =>
    `        <li><a href="#${section.id}">${esc(plain(en.nav.labels[section.id]))}</a></li>`,
).join('\n');

const communityLinks = en.nav.community
  .map(
    link =>
      `        <li><a href="${esc(link.href)}" target="_blank" rel="noopener noreferrer">${esc(
        plain(link.label),
      )}</a></li>`,
  )
  .join('\n');

const heroBadges = en.hero.badges.map(b => `        <li>${esc(plain(b))}</li>`).join('\n');

const heroCtas = en.hero.cta
  .map(c => `      <a href="${esc(c.href)}">${esc(c.label)}</a>`)
  .join('\n');

const tldr = en.hero.tldr.items
  .map(item => `        <li><b>${esc(item.b)}</b>${esc(item.text)}</li>`)
  .join('\n');

const tracks = LECTURES.tracks
  .map(track => {
    const items = track.lectures
      .map(lec => {
        const head = `<b>${esc(LECTURES.lectureLabel)} ${lec.num} — ${esc(lec.title)}</b> (${
          lec.ready ? esc(LECTURES.liveLabel) : esc(LECTURES.comingSoon)
        })`;
        const link =
          lec.ready && lec.url
            ? `\n          <a href="${esc(lec.url)}" target="_blank" rel="noopener noreferrer">${esc(
                LECTURES.openLecture,
              )}</a>`
            : '';
        return `        <li>\n          ${head}\n          <p>${esc(lec.desc)}</p>${link}\n        </li>`;
      })
      .join('\n');
    return `      <h3>${esc(track.title)}</h3>\n      <p>${esc(
      track.lead,
    )}</p>\n      <ol>\n${items}\n      </ol>`;
  })
  .join('\n\n');

const challengeLevels = en.codingChallenges.levels
  .map(level => {
    const items = level.items.map(c => `        <li>${esc(c.title)}</li>`).join('\n');
    return `      <h3>${esc(level.label)}</h3>\n      <p>${esc(
      level.blurb,
    )}</p>\n      <ol>\n${items}\n      </ol>`;
  })
  .join('\n\n');

/** Section bodies, keyed by id, rendered in SECTIONS order. */
const BODIES: Record<string, string> = {
  resume: `      <h2>${esc(en.resume.title)}</h2>\n      <p>${esc(en.resume.lead)}</p>`,
  'lecture-series': `      <h2>${esc(LECTURES.title)}</h2>\n      <p>${esc(
    LECTURES.lead,
  )}</p>\n\n${tracks}`,
  'interview-talk': `      <h2>${esc(en.interview.title)}</h2>\n      <p>${esc(en.interview.lead)}</p>`,
  'interview-questions': `      <h2>${esc(EN_BANK.title)}</h2>\n      <p>${esc(EN_BANK.lead)}</p>`,
  'coding-challenges': `      <h2>${esc(en.codingChallenges.title)}</h2>\n      <p>${esc(
    en.codingChallenges.lead,
  )}</p>\n\n${challengeLevels}`,
  setup: `      <h2>${esc(en.setup.title)}</h2>\n      <p>${esc(en.setup.lead)}</p>`,
};

const sections = SECTIONS.map(
  section => `    <section id="${section.id}">\n${BODIES[section.id]}\n    </section>`,
).join('\n\n');

const block = `${START}
  <!--
    Static pre-rendered content for crawlers and social bots. The React app
    replaces this on mount, so nobody ever sees it and nothing about the page
    reveals when it goes stale.

    GENERATED by scripts/generate-prerender.ts — do not edit by hand.
    Run \`pnpm run generate-prerender\` after changing lectures, challenges,
    the section order, or the hero copy.
  -->
  <nav aria-label="Primary">
    <a href="#" aria-label="${esc(en.nav.logo)} home">${esc(en.nav.logo)}</a>
    <ul>
${navLinks}
    </ul>
    <ul aria-label="Community links">
${communityLinks}
    </ul>
  </nav>

  <header id="hero">
    <h1>${esc(en.hero.h1Line1)}<br>${esc(en.hero.h1Line2)}</h1>
    <p>${esc(en.hero.p)}</p>
    <ul aria-label="Features">
${heroBadges}
    </ul>
    <div>
${heroCtas}
    </div>
    <div>
      <b>${esc(en.hero.tldr.heading)}</b>
      <ul>
${tldr}
      </ul>
    </div>
  </header>

  <main id="main-content">

${sections}

  </main>

  <footer id="site-footer">
    <p>© ${en.footer.year} ${esc(en.footer.text)} <a href="${esc(
      en.footer.authorHref,
    )}" target="_blank" rel="noopener noreferrer">${esc(en.footer.authorName)}</a> ${esc(
      en.footer.suffix,
    )}</p>
  </footer>
  ${END}`;

const html = readFileSync(indexPath, 'utf8');
const start = html.indexOf(START);
const end = html.indexOf(END);

if (start === -1 || end === -1) {
  throw new Error(
    `Could not find the ${START} / ${END} markers in index.html. ` +
      'They delimit the generated block; restore them before running this.',
  );
}

const next = html.slice(0, start) + block + html.slice(end + END.length);
writeFileSync(indexPath, next);

const lectureCount = LECTURES.tracks.reduce((n, t) => n + t.lectures.length, 0);
const challengeCount = en.codingChallenges.levels.reduce((n, l) => n + l.items.length, 0);
console.log(
  `Prerender rewritten: ${SECTIONS.length} sections, ${lectureCount} lectures, ` +
    `${challengeCount} coding challenges.`,
);
