-- Content tables for the academy's three public collections, and for the
-- worked-example slides the lecture decks read directly.
--
-- The seed script (`academy-seed.sql`) truncates and fills these; it never
-- created them, and nothing else in this repository did either — which is why a
-- fresh Supabase project answers `/api/content/*` with a 503 that reads like an
-- outage rather than an empty database.
--
-- Every column name here is load-bearing: `server/app/content_store.py` asks
-- PostgREST for exact `select=` lists, and a rename that is not made in both
-- places returns rows the API cannot read. `tests/unit/contentSchema.spec.ts`
-- fails when the two disagree.
--
-- Apply once, before the seed:
--
--     psql "$DATABASE_URL" -f scripts/src/academy-schema.sql
--     psql "$DATABASE_URL" -f scripts/src/academy-seed.sql

begin;

-- Parents carry the language; children inherit it through their parent, which
-- is why the API filters parents by `lang` and children by parent id.
--
-- The ids are identity columns rather than plain bigints because the seed
-- assigns them explicitly and then calls `setval('<table>_id_seq', …)` on its
-- last few lines, so that a row added by hand afterwards does not collide with
-- one the seed wrote. Without a sequence those calls abort the transaction and
-- nothing lands.
create table if not exists question_bank_stages (
  id       bigint generated by default as identity primary key,
  lang     text   not null check (lang in ('en', 'he')),
  position integer not null,
  icon     text   not null,
  title    text   not null,
  unique (lang, position)
);

create table if not exists question_bank_items (
  id       bigint generated by default as identity primary key,
  stage_id bigint not null references question_bank_stages (id) on delete cascade,
  position integer not null,
  question text   not null,
  hint     text   not null,
  -- One paragraph per element. `text[]` rather than a joined string, because the
  -- reader is shown paragraphs and a delimiter would have to be chosen, escaped
  -- and split back out on every read.
  answer   text[] not null,
  unique (stage_id, position)
);

create table if not exists coding_challenge_levels (
  id       bigint generated by default as identity primary key,
  lang     text   not null check (lang in ('en', 'he')),
  position integer not null,
  label    text   not null,
  blurb    text   not null,
  unique (lang, position)
);

create table if not exists coding_challenges (
  id         bigint generated by default as identity primary key,
  level_id   bigint not null references coding_challenge_levels (id) on delete cascade,
  position   integer not null,
  title      text   not null,
  prompt     text   not null,
  hint       text   not null,
  code       text   not null,
  complexity text   not null,
  unique (level_id, position)
);

create table if not exists lecture_tracks (
  id       bigint generated by default as identity primary key,
  lang     text   not null check (lang in ('en', 'he')),
  position integer not null,
  title    text   not null,
  lead     text   not null,
  unique (lang, position)
);

create table if not exists lecture_items (
  id          bigint generated by default as identity primary key,
  track_id    bigint not null references lecture_tracks (id) on delete cascade,
  position    integer not null,
  num         integer not null,
  ready       boolean not null default false,
  title       text   not null,
  description text   not null,
  -- Null for a lecture hosted on this site; set for the ones that are not ours
  -- to move. The API omits the key entirely when it is null.
  url         text,
  unique (track_id, position)
);

-- Worked-example slide content, read straight from PostgREST by the lecture
-- decks rather than through `/api/content/*` — `artifacts/ai-testing-lecture-*/
-- src/lib/examplesClient.ts` holds the anon key and calls `.single()`, so a
-- missing row is an error and the slide renders "Example content unavailable".
--
-- Keyed by the lecture it belongs to and the slide position inside that deck.
-- The deck supplies both: `LECTURE_ITEM_ID` in its `examplesClient.ts` names
-- the `lecture_items` row per language, and each slide passes its own position
-- to `fetchLectureExample`. Neither is derivable from the other, which is why
-- `tests/unit/lectureExamples.spec.ts` checks the seed against the call sites.
create table if not exists lecture_examples (
  id              bigint generated by default as identity primary key,
  lecture_item_id bigint not null references lecture_items (id) on delete cascade,
  lang            text   not null check (lang in ('en', 'he')),
  position        integer not null,
  eyebrow         text   not null default 'WORKED EXAMPLE',
  title           text   not null,
  bullets         text[] not null default '{}',
  -- The panel list as the deck renders it: `[{ rows: [{label, value}],
  -- verdict?: {status, note} }]`. jsonb rather than more tables because no
  -- query ever looks inside it — one row is fetched whole and handed to the
  -- component, which is the shape `LectureExample` already describes.
  panels          jsonb  not null,
  created_at      timestamptz not null default now(),
  unique (lecture_item_id, lang, position)
);

-- The API reads with the anon key, so PostgREST needs both a grant and a row
-- policy. Without them the tables exist, the seed succeeds, and every request
-- still comes back empty — the same 503 as having no tables at all.
--
-- Read-only and public on purpose: this is course content, served to anyone who
-- opens the site. Writes stay with the service role, which the seed uses.
alter table question_bank_stages     enable row level security;
alter table question_bank_items      enable row level security;
alter table coding_challenge_levels  enable row level security;
alter table coding_challenges        enable row level security;
alter table lecture_tracks           enable row level security;
alter table lecture_items            enable row level security;
alter table lecture_examples         enable row level security;

do $$
declare t text;
begin
  foreach t in array array[
    'question_bank_stages', 'question_bank_items',
    'coding_challenge_levels', 'coding_challenges',
    'lecture_tracks', 'lecture_items', 'lecture_examples'
  ] loop
    execute format('grant select on table %I to anon, authenticated;', t);
    if not exists (
      select 1 from pg_policies where tablename = t and policyname = 'public read'
    ) then
      execute format('create policy "public read" on %I for select using (true);', t);
    end if;
  end loop;
end $$;

commit;
