insert into question_bank_items (id, stage_id, position, question, hint, answer) values (140, 10, 4, 'איך היית מעריך את איכות פיצ''ר ה-AI מעבר ל-pass/fail פשוט?', 'בנו ערכת הערכה עם ציונים, ספים ומגמות — pass/fail הוא הצורה הלא נכונה למערכת סטוכסטית.', ARRAY['בנו ערכת הערכה מתויגת שמשקפת שימוש אמיתי — מקרים טיפוסיים, מקרים קשים, מקרים תוקפניים, וכל רגרסיה שכבר שחררתם — ונהלו לה גרסאות כמו לקוד.', 'תנו ציון לכל ממד במקום לכווץ למספר אחד: הצלחת משימה, עיגון עובדתי ושיעור הזיות, תקינות פורמט, בטיחות ונכונות סירוב, זמן תגובה ועלות לבקשה.', 'השתמשו בציון מדורג: התאמה מדויקת כשיש תשובה נכונה אחת, דמיון או רובריקה כשאין, ו-LLM-as-judge עם רובריקה כתובה — מאומת מול תיוג אנושי, כי שופט לא מאומת רק מעביר את בעיית האמון למקום אחר.', 'שערו על אגרגטים עם ספים מפורשים ולא על מקרים בודדים: "לפחות 92% הצלחת משימה ולכל היותר 2% הזיות על 300 מקרים", והריצו מחדש בכל שינוי פרומפט או מודל כדי לתפוס סחיפה.', 'סגרו את הלולאה עם אותות מפרודקשן — אגודל למטה, שיעור הסלמה, ניסיונות חוזרים, העברה לאדם — והזינו כל כשל בחזרה לערכת ההערכה. דווחו התפלגות ומגמה, לעולם לא סימן ירוק בודד.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (141, 10, 5, 'מהו RAG, ואילו מצבי כשל היית בודק?', 'Retrieval-augmented generation נכשל באחזור לא פחות מבייצור.', ARRAY['RAG מעגן תשובה במסמכים שנשלפים בזמן השאילתה, כך שהמודל מצטט את הנתונים שלכם במקום את זיכרון האימון. זה מפצל את המערכת ל-retriever ו-generator, לכל אחד כשלים משלו.', 'בדקו אחזור: האם הוא שולף את הקטעים הרלוונטיים, ומה קורה כשאין רלוונטי (צריך לומר זאת, לא להמציא)? Chunking, embeddings ודירוג כולם נשברים כאן.', 'בדקו בייצור מעל ההקשר שנשלף: התשובה חייבת להישאר מעוגנת במה שנשלף, לצטט נכון, לסרב כשההקשר ריק, ולעמוד ב-injection דרך מסמך מורעל.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (142, 10, 6, 'איך אתה בודק במפורש הזיות?', 'מדדו עיגון ותנו למודל דרך לומר "אני לא יודע".', ARRAY['בנו ערכת הערכה עם שאלות בעלות תשובה ידועה, וחשוב — כאלה שאין להן תשובה, שבהן המודל חייב להימנע ולא להמציא. שיעור ההימנעות חשוב כמו שיעור הדיוק.', 'נקדו עיגון עובדתי: בדקו את התשובה מול המקור (ב-RAG, שהיא נתמכת בהקשר שנשלף) עם בדיקות מחרוזת/היקש או שופט-LLM שאומת מול תיוג אנושי.', 'עקבו אחר שיעור הזיות על הסט ושערו עליו. הפחיתו אותו עם עיגון, ציטוטים, temperature נמוך ופרומפטים שמתירים "אני לא יודע" — ואז הוכיחו את ההפחתה עם המדד.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (143, 10, 7, 'מהי ערכת הערכה (golden set), ואיך בונים אותה?', 'נהלו לה גרסאות כמו קוד; הצמיחו אותה מכשלים אמיתיים.', ARRAY['סט אצור של קלטים עם פלטים צפויים או קריטריוני ציון שמשקף שימוש אמיתי — מקרים טיפוסיים, קשים, תוקפניים, וכל רגרסיה שכבר שחררתם.', 'בנו אותה מלוגים של פרודקשן, מומחי תחום ותקריות עבר; תייגו בקפידה, שמרו מייצגת, ונהלו גרסאות כך שציון ניתן להשוואה על פני שינויי מודל ופרומפט.', 'הצמיחו אותה ברציפות: כל כשל חדש הופך למקרה קבוע, כך שהסוויטה מתחזקת לאורך זמן. ערכת הערכה מיושנת מפסיקה בשקט להגן עליכם כשהשימוש משתנה.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (144, 10, 8, 'איך אתה בודק סוכן AI שקורא לכלים / פונקציות?', 'בדקו את ההחלטות והחיווט בנפרד מהפרוזה של המודל.', ARRAY['וודאו בחירת כלי וארגומנטים: בהינתן קלט, האם קרא לפונקציה הנכונה עם פרמטרים תקינים ותואמי-סכימה — והאם *לא* קרא לכזו שאסור?', 'החליפו את הכלים ב-stubs כך שהבדיקות דטרמיניסטיות וזולות, וודאו שהסוכן מטפל בשגיאות כלי, תוצאות ריקות ו-timeouts בחן במקום להיכנס ללולאה או להמציא תוצאה.', 'הגנו על החלקים המסוכנים: הרשאות על כל כלי (injection מוצלח אסור שיאפשר לו לפעול מעבר לזכויות המשתמש), מגבלות לולאה ועלות, וללא פעולה בלתי-הפיכה בלי אישור.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (145, 10, 9, 'מהו LLM-as-a-judge, ומהם המכשולים?', 'שימושי לציון עמום, אך שופט לא-מאומת רק מזיז את בעיית האמון.', ARRAY['שימוש במודל חזק כדי לנקד פלט של מודל אחר מול רובריקה — שימושי היכן שהתאמה-מדויקת לא עובדת, כמו מועילוּת או טון.', 'המכשולים אמיתיים: שופטים מוטים לטובת תשובות ארוכות או שנכתבו על ידיהם, רגישים לניסוח הפרומפט ולסדר האפשרויות, ולא-דטרמיניסטיים בעצמם.', 'מתנו על ידי אימות השופט מול תיוג אנושי, מתן רובריקה מדויקת, קיבוע temperature, שליטה בהטיית מיקום, ושמירתו לממדים העמומים בלבד תוך שימוש בבדיקות דטרמיניסטיות למבנה ובטיחות.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (146, 10, 10, 'איך אתה בודק פיצ׳ר AI להטיה והוגנות?', 'שנו רק את המאפיין המוגן והשוו תוצאות.', ARRAY['השתמשו בבדיקות counterfactual: קחו את אותו קלט ושנו רק מאפיין מוגן (שם, מגדר, רמז אתני) וודאו שההחלטה או הטון לא משתנים כשלא צריך.', 'מדדו תוצאות על פני קבוצות על סט מייצג — לא רק אנקדוטות — ושימו לב לשיעורי איכות או סירוב שנבדלים לפי קבוצה.', 'כסו גם נזק ייצוגי: סטריאוטיפים, הטיה בתוכן שנוצר, והעובדה שנתוני אימון מקודדים הטיה היסטורית. הגדירו מה "הוגן" עבור הפיצ׳ר מראש, כי זו החלטת מוצר, לא מדד.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (147, 10, 11, 'איך אתה כותב assertions אמינות מול מודל לא-דטרמיניסטי?', 'בדקו את החוזה ותכונות, לעולם לא את המשפט המדויק.', ARRAY['קבעו את מה שאפשר — גרסת מודל, temperature, seed היכן שנתמך — והקליטו/שחזרו תגובות אמיתיות כ-fixtures כך שרוב הבדיקות מהירות, חינמיות ודטרמיניסטיות.', 'בדקו תכונות, לא מחרוזות: JSON תקין מול סכימה, שדות חובה קיימים, אין תוכן אסור, מגבלות אורך ושפה, וסירוב כשצריך לסרב.', 'לחלק העמום באמת, הריצו ערכת הערכה מנוקדת לפי לוח זמנים עם ספים וסבילוּת, והתייחסו לירידה בציון כאות רגרסיה ולא כ-build אדום בודד.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (148, 10, 12, 'אילו מעקות בטיחות היית בודק בצ׳אטבוט פונה-לקוחות?', 'הניחו שמשתמשים יהיו תוקפניים ויצירתיים.', ARRAY['בטיחות תוכן: הוא מסרב לבקשות מזיקות, לא-חוקיות או שנאה, ועומד ב-jailbreaks ובמסגורי משחק-תפקידים שמנסים לדבר אותו החוצה מהמדיניות.', 'גבול ופרטיות: הוא נשאר בנושא, לא ממציא מדיניות או מבטיח דברים שהעסק לא יכבד, ולעולם לא מדליף פרומפטים מערכתיים, נתונים של משתמשים אחרים או סודות.', 'עמידות והסלמה: injection דרך קלט משתמש או מסמך מודבק מוכל, והוא מעביר לאדם כשלא בטוח במקום לנחש בביטחון. התייחסו לכל עקיפה אמיתית כמקרה רגרסיה קבוע.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (149, 10, 13, 'איך אתה בודק מגבלות חלון-הקשר, קיטום וקלטים ארוכים?', 'מה שנופל בשקט מקצה הפרומפט הוא באג אמיתי.', ARRAY['בדקו בגבול החלון ומעבר לו: המערכת חייבת לקטום או לסכם במכוון, לא להשמיט בשקט את השאלה האמיתית של המשתמש או את ההוראות המערכתיות.', 'בחנו את אפקט ה"אבוד באמצע" — מודלים מקדישים פחות תשומת לב לאמצע הקשר ארוך — על ידי מיקום העובדה המרכזית בהתחלה, באמצע ובסוף ובדיקה שהיא עדיין בשימוש.', 'וודאו טיפול חינני בגלישה (שגיאה ברורה או אסטרטגיית chunking, לעולם לא קריסה), ושימו לב לעלות ו-latency, שגדלים עם אורך הקלט.']::text[]);
insert into question_bank_items (id, stage_id, position, question, hint, answer) values (150, 10, 14, 'איך אתה מנטר פיצ׳ר AI בפרודקשן לסחיפה ולדעיכת איכות?', 'הערכה אופליין היא תמונת-רגע; בפרודקשן האיכות באמת נשחקת.', ARRAY['תעדו קלטים, פלטים ואותות, ושימו לב לסחיפת קלט (משתמשים שואלים דברים חדשים) ולסחיפת פלט (המודל או עדכון-ספק שקט משנים התנהגות).', 'עקבו אחר מדדי-איכות ברציפות: אגודל למטה, שיעורי הסלמה וניסיונות חוזרים, שיעור סירוב, latency ועלות — והתריעו על שינויי מגמה, לא על אירועים בודדים.', 'הריצו הערכה מתוזמנת מול ה-golden set לתפוס רגרסיות שעדכון-ספק הכניס, דגמו תעבורה אמיתית לסקירה אנושית, והזינו כל כשל שהתגלה בחזרה לערכת ההערכה.']::text[]);
insert into coding_challenge_levels (id, lang, position, label, blurb) values (1, 'en', 0, 'Level 1 — Fundamentals', 'Lists, dicts and a little recursion. Nothing here needs a clever trick, only a clean single pass.');
insert into coding_challenges (id, level_id, position, title, prompt, hint, code, complexity) values (1, 1, 0, '1. Deduplicate test IDs, preserving order', 'Given a list of test case IDs that may contain duplicates, return a new list with duplicates removed, preserving first-seen order.', 'Use a set to track what has been seen while iterating once and appending only unseen items to the result list.', 'def dedupe(ids):
    seen = set()
    result = []
    for i in ids:
        if i not in seen:
            seen.add(i)
            result.append(i)
    return result', 'Time: O(n) average (set lookups are O(1) amortized). Space: O(n) for the seen set and result.');
insert into coding_challenges (id, level_id, position, title, prompt, hint, code, complexity) values (2, 1, 1, '2. Find the first duplicate test ID', 'Given a large list of test IDs, return the first ID that appears more than once, or None if there are no duplicates.', 'Avoid the naive O(n^2) nested-loop check — a single pass with a set gets it done in one sweep.', 'def first_duplicate(ids):
    seen = set()
    for i in ids:
        if i in seen:
            return i
        seen.add(i)
    return None', 'Time: O(n). Space: O(n) for the seen set.');
insert into coding_challenges (id, level_id, position, title, prompt, hint, code, complexity) values (3, 1, 2, '3. Flatten a nested test suite', 'Test suites can nest suites inside suites arbitrarily deep (a tree of lists). Write a function that flattens this structure into a single list of leaf test names.', 'Recursion works naturally on a tree: if a node is a list, recurse into each child; if it is a plain value (a leaf test name), add it to the result.', 'def flatten_suite(node):
    result = []
    def walk(n):
        if isinstance(n, (list, tuple)):
            for child in n:
                walk(child)
        else:
            result.append(n)
    walk(node)
    return result', 'Time: O(n) where n = total number of nodes in the tree. Space: O(d) recursion stack (d = tree depth) plus O(n) for the output.');