import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { test, expect, labelApiSuite } from '../support/apiFixtures';
import { parse as parseYaml } from 'yaml';
import * as apiZod from '@workspace/api-zod';

/**
 * Three things have to agree, and nothing in the build makes them:
 *
 *   lib/api-spec/openapi.yaml  →  lib/api-zod (generated by orval)  →  the running server
 *
 * The spec is hand-written, the Zod schemas are regenerated by an explicit
 * `codegen` run, and the FastAPI routes are hand-written too. These tests fail
 * when any pair of the three drifts apart.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const specPath = path.resolve(here, '..', '..', 'lib', 'api-spec', 'openapi.yaml');

interface OpenApiSpec {
  openapi: string;
  servers: Array<{ url: string }>;
  paths: Record<string, Record<string, OpenApiOperation>>;
  components: {
    schemas: Record<string, OpenApiSchema>;
    responses?: Record<string, OpenApiResponse>;
  };
}

interface OpenApiResponse {
  $ref?: string;
  content?: Record<string, { schema?: { $ref?: string } }>;
}

interface OpenApiOperation {
  operationId: string;
  responses: Record<string, OpenApiResponse>;
}

interface OpenApiSchema {
  type: string;
  properties?: Record<string, unknown>;
  required?: string[];
}

const spec = parseYaml(readFileSync(specPath, 'utf8')) as OpenApiSpec;
const basePath = spec.servers[0]!.url;

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

interface DocumentedOperation {
  method: (typeof HTTP_METHODS)[number];
  route: string;
  url: string;
  operation: OpenApiOperation;
}

const documented: DocumentedOperation[] = Object.entries(spec.paths).flatMap(([route, methods]) =>
  HTTP_METHODS.filter(method => methods[method]).map(method => ({
    method,
    route,
    url: `${basePath}${route}`,
    operation: methods[method]!,
  })),
);

/** Orval names a response schema after the operation: healthCheck → HealthCheckResponse. */
function generatedSchemaFor(operationId: string): unknown {
  const name = `${operationId[0]!.toUpperCase()}${operationId.slice(1)}Response`;
  return (apiZod as Record<string, unknown>)[name];
}

/** Follows one `#/components/<kind>/<Name>` pointer. */
function deref<T>(ref: string | undefined, kind: 'schemas' | 'responses'): T | undefined {
  if (!ref) return undefined;
  const name = ref.split('/').pop()!;
  return (spec.components[kind] as Record<string, unknown> | undefined)?.[name] as T | undefined;
}

/**
 * The schema the spec documents for the status that actually came back.
 *
 * Not the 200 schema. Orval emits one schema per operation — the success one —
 * so validating every reply against it says "the error body is not a question
 * bank", which is true and useless. `/healthz` hid this for as long as it was
 * the only documented route, because it has no other status to return.
 */
function specSchemaForStatus(
  operation: OpenApiOperation,
  status: number,
): OpenApiSchema | undefined {
  let response: OpenApiResponse | undefined = operation.responses[String(status)];
  if (response?.$ref) response = deref<OpenApiResponse>(response.$ref, 'responses');
  return deref<OpenApiSchema>(response?.content?.['application/json']?.schema?.$ref, 'schemas');
}

/** Reports what the spec's schema says is wrong with `body`, at the top level. */
function violations(schema: OpenApiSchema, body: unknown): string[] {
  if (schema.type !== 'object') return [];
  if (typeof body !== 'object' || body === null) return ['body is not an object'];
  const record = body as Record<string, unknown>;
  const problems: string[] = [];
  for (const key of schema.required ?? []) {
    if (!(key in record)) problems.push(`missing required property "${key}"`);
  }
  for (const key of Object.keys(record)) {
    if (schema.properties && !(key in schema.properties)) {
      problems.push(`undocumented property "${key}"`);
    }
  }
  return problems;
}

function isZodObject(value: unknown): value is {
  strict(): { parse(data: unknown): unknown };
  shape: Record<string, unknown>;
} {
  return typeof value === 'object' && value !== null && 'shape' in value;
}

test.beforeEach(async () => {
  await labelApiSuite('OpenAPI contract');
});

test.describe('the spec itself', () => {
  test('documents at least one operation', () => {
    expect(documented.length).toBeGreaterThan(0);
  });

  test('is served from the path the server mounts its router on', () => {
    // The Python application mounts every public route below /api.
    expect(basePath).toBe('/api');
  });
});

test.describe('spec ↔ generated Zod schemas', () => {
  for (const { method, route, operation } of documented) {
    test(`${method.toUpperCase()} ${route} has a generated response schema`, () => {
      expect(
        generatedSchemaFor(operation.operationId),
        `no schema exported for operationId "${operation.operationId}" — run ` +
          '`pnpm --filter @workspace/api-spec run codegen`',
      ).toBeDefined();
    });
  }

  test('the health schema has the same fields the spec declares', () => {
    const specSchema = spec.components.schemas.HealthStatus!;
    const generated = apiZod.HealthCheckResponse;

    expect(Object.keys(generated.shape).sort()).toEqual(
      Object.keys(specSchema.properties ?? {}).sort(),
    );
    expect(specSchema.required).toEqual(['status']);
  });
});

test.describe('spec ↔ running server', () => {
  for (const { method, route, url, operation } of documented) {
    test(`${method.toUpperCase()} ${route} answers with a documented status`, async ({ api }) => {
      const response = await api.fetch(url, { method: method.toUpperCase() });

      expect(
        Object.keys(operation.responses),
        `${method.toUpperCase()} ${url} answered ${response.status()}`,
      ).toContain(String(response.status()));
    });

    test(`${method.toUpperCase()} ${route} answers with a documented media type`, async ({
      api,
    }) => {
      const response = await api.fetch(url, { method: method.toUpperCase() });
      const documentedTypes = Object.keys(
        operation.responses[String(response.status())]?.content ?? {},
      );

      if (documentedTypes.length === 0) return;
      expect(documentedTypes.some(type => response.headers()['content-type']?.includes(type))).toBe(
        true,
      );
    });

    test(`${method.toUpperCase()} ${route} returns a body its schema accepts`, async ({ api }) => {
      const response = await api.fetch(url, { method: method.toUpperCase() });
      const status = response.status();
      const body = await response.json();

      const specSchema = specSchemaForStatus(operation, status);
      test.skip(!specSchema, `no JSON schema documented for ${status}`);

      // Checked against the status that came back, so an error reply is judged
      // by the error schema and not by the success one.
      expect(violations(specSchema!, body), `body does not match the ${status} schema`).toEqual([]);

      // On success, also run orval's generated schema, which is the stricter of
      // the two: it types every field and every nested one, where the check
      // above only sees the top level. An undocumented extra field is drift too,
      // and a client round-tripping the payload will silently drop it.
      const generated = generatedSchemaFor(operation.operationId);
      if (status === 200 && isZodObject(generated)) {
        expect(() =>
          (generated as { strict(): { parse(d: unknown): unknown } }).strict().parse(body),
        ).not.toThrow();
      }
    });
  }
});

/**
 * Routes the server implements that the spec says nothing about. They are
 * listed here deliberately: the point is that the gap is visible and reviewed,
 * not that it is silently tolerated.
 *
 * `/stripe/seed` and nothing else is omitted from the probe below — it is a
 * write endpoint, and a test suite should not be able to create products. What
 * keeps it from being called is no longer this list, though: the route is
 * behind an admin token now, and `tests/api/adminAuth.spec.ts` is what asserts
 * that. This entry is back to being about spec drift and nothing else.
 */
const UNDOCUMENTED_ROUTES: Array<{ method: 'GET' | 'POST'; route: string; probe?: boolean }> = [
  { method: 'GET', route: '/auth/config' },
  { method: 'GET', route: '/ai/config' },
  { method: 'POST', route: '/ai/generate' },
  { method: 'GET', route: '/stripe/prices' },
  { method: 'POST', route: '/stripe/checkout' },
  { method: 'POST', route: '/stripe/webhook' },
  { method: 'POST', route: '/stripe/seed', probe: false },
  { method: 'GET', route: '/entitlements/course' },
];

test.describe('undocumented routes', () => {
  test('are still absent from the spec', () => {
    // When one of these is finally documented, delete it from the list above —
    // it will then be covered by the spec-driven tests instead.
    for (const { route } of UNDOCUMENTED_ROUTES) {
      expect(Object.keys(spec.paths), `${route} is documented now`).not.toContain(route);
    }
  });

  for (const entry of UNDOCUMENTED_ROUTES.filter(r => r.probe !== false)) {
    test(`${entry.method} ${entry.route} is implemented`, async ({ api }) => {
      const response = await api.fetch(`${basePath}${entry.route}`, {
        method: entry.method,
        ...(entry.method === 'POST' ? { data: {} } : {}),
      });

      expect(response.status(), 'route is missing entirely').not.toBe(404);
    });
  }
});
