"""Course purchasers, and what to do about each of them.

The recommendation is generated by the same AI gateway the public tools use,
with one deliberate difference: the model is never shown who the customer is.
An email address is what makes this record personal data, and none of the
advice depends on it — "bought eleven days ago and has never signed in" is the
whole of what the question is about. So the profile handed to the provider
carries elapsed time and account state and nothing that identifies anyone.
"""

from __future__ import annotations

import logging
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any

from .ai_gateway import AiGateway
from .errors import ServiceError
from .schemas import GenerateBody

logger = logging.getLogger(__name__)

RECOMMENDATION_TOKENS = 700

SYSTEM_PROMPT = (
    "You advise the owner of an online QA-automation course on what to do next "
    "for one customer. You are given anonymous facts about a single purchase. "
    "Reply with JSON only: an object with an `actions` array of at most four "
    'items, each {"action": string, "why": string, "priority": "high"|'
    '"medium"|"low"}. Be specific and practical. Never invent details you '
    "were not given, and never ask for the customer's identity."
)

# The operator reads this screen in whichever language the academy is showing,
# so the advice has to arrive in that language. Only the `action` and `why`
# strings are translated — the JSON keys and the priority values are a contract.
LANGUAGE_INSTRUCTION = {
    "en": "Write `action` and `why` in English.",
    "he": "Write `action` and `why` in Hebrew, and nothing else in Hebrew.",
}


@dataclass(frozen=True)
class Customer:
    """One purchase, as the admin screen shows it."""

    id: str
    email: str
    purchased_at: datetime
    amount_total: int
    currency: str
    linked_account: bool

    @property
    def days_since_purchase(self) -> int:
        return max(0, (datetime.now(UTC) - self.purchased_at).days)

    @classmethod
    def from_row(cls, row: dict) -> Customer:
        purchased_at = row["purchased_at"]
        if purchased_at.tzinfo is None:
            purchased_at = purchased_at.replace(tzinfo=UTC)
        return cls(
            id=row["id"],
            email=row["email"],
            purchased_at=purchased_at,
            amount_total=row["amount_total"],
            currency=row["currency"],
            linked_account=bool(row["google_subject"]),
        )

    def public(self) -> dict[str, Any]:
        """What the admin screen renders. The operator may see the email."""
        return {
            "id": self.id,
            "email": self.email,
            "purchasedAt": self.purchased_at.isoformat(),
            "amountTotal": self.amount_total,
            "currency": self.currency,
            "linkedAccount": self.linked_account,
            "daysSincePurchase": self.days_since_purchase,
        }

    def anonymous_profile(self) -> dict[str, Any]:
        """What the model may see. Deliberately carries no identifier."""
        return {
            "daysSincePurchase": self.days_since_purchase,
            "hasSignedIn": self.linked_account,
            "amountPaid": self.amount_total / 100,
            "currency": self.currency,
        }


PurchaseLister = Callable[[], Awaitable[list[dict]]]
PurchaseFinder = Callable[[str], Awaitable[dict | None]]


class CustomerService:
    def __init__(self, list_purchases: PurchaseLister, find_purchase: PurchaseFinder) -> None:
        self._list_purchases = list_purchases
        self._find_purchase = find_purchase

    async def listing(self) -> list[dict[str, Any]]:
        try:
            rows = await self._list_purchases()
        except Exception as exc:
            logger.exception("Could not read course purchases")
            raise ServiceError("Could not read customers", 500) from exc
        return [Customer.from_row(row).public() for row in rows]

    async def find(self, purchase_id: str) -> Customer:
        try:
            row = await self._find_purchase(purchase_id)
        except Exception as exc:
            logger.exception("Could not read a course purchase")
            raise ServiceError("Could not read the customer", 500) from exc
        if row is None:
            raise ServiceError("No such customer", 404)
        return Customer.from_row(row)


class RecommendationService:
    """Turns one anonymous purchase profile into a short list of actions."""

    def __init__(self, customers: CustomerService, ai: AiGateway) -> None:
        self._customers = customers
        self._ai = ai

    async def for_customer(self, purchase_id: str, language: str = "en") -> dict[str, Any]:
        customer = await self._customers.find(purchase_id)
        instruction = LANGUAGE_INSTRUCTION.get(language, LANGUAGE_INSTRUCTION["en"])
        body = GenerateBody.model_validate(
            {
                "system": f"{SYSTEM_PROMPT} {instruction}",
                "messages": [{"role": "user", "content": _describe(customer)}],
                "maxTokens": RECOMMENDATION_TOKENS,
            }
        )
        outcome = await self._ai.generate(body)
        if outcome.status != 200:
            raise ServiceError(
                "Could not generate recommendations for this customer", outcome.status
            )
        return {"customerId": customer.id, "text": outcome.payload.get("text", "")}


def _describe(customer: Customer) -> str:
    profile = customer.anonymous_profile()
    return (
        f"Days since purchase: {profile['daysSincePurchase']}. "
        f"Has signed in to the academy: {'yes' if profile['hasSignedIn'] else 'no'}. "
        f"Paid: {profile['amountPaid']:.2f} {profile['currency'].upper()}."
    )
