-- Everything this API owns in Postgres.
--
-- `initialize_database()` runs this file at boot, every boot, so every
-- statement is idempotent and the file is the whole story: there is no
-- migration history to replay and no ordering to remember.
--
-- It is applied to the same Supabase project that holds the content tables,
-- and that is the reason for the security block at the bottom. `public` is the
-- schema PostgREST exposes, so a table created here without row level security
-- is a table the anon key can read over HTTPS — and these tables hold customer
-- email addresses, purchase records and per-person activity. None of them is
-- content, none of them is public, and none of them is ever read with the anon
-- key: the API connects as `postgres` over psycopg, which owns these tables and
-- therefore bypasses their policies.

-- Money. A purchase is the record that someone paid, and it is the only source
-- of truth for whether they may open the course.
CREATE TABLE IF NOT EXISTS course_purchases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  checkout_session_id text NOT NULL UNIQUE,
  payment_intent_id text,
  stripe_customer_id text,
  email text NOT NULL,
  google_subject text,
  product_id text NOT NULL,
  price_id text,
  amount_total integer NOT NULL,
  currency text NOT NULL,
  purchased_at timestamptz NOT NULL DEFAULT now(),
  retention_until timestamptz
);
CREATE INDEX IF NOT EXISTS course_purchases_email_idx ON course_purchases (email);
CREATE INDEX IF NOT EXISTS course_purchases_google_subject_idx ON course_purchases (google_subject);
CREATE INDEX IF NOT EXISTS course_purchases_retention_idx ON course_purchases (retention_until);

-- Quotas, shared between workers. One row per bucket and caller, reused in
-- place; `hit_rate_limit` rolls the window forward rather than inserting again.
CREATE TABLE IF NOT EXISTS api_rate_limits (
  bucket text NOT NULL,
  key_hash text NOT NULL,
  window_started timestamptz NOT NULL DEFAULT now(),
  hits integer NOT NULL DEFAULT 0,
  PRIMARY KEY (bucket, key_hash)
);
CREATE INDEX IF NOT EXISTS api_rate_limits_window_idx ON api_rate_limits (window_started);

-- Who signed in, keyed by the Google subject — the one identifier that stays
-- the same when someone changes their name, their picture or their email.
--
-- Deliberately thin. The session cookie already carries the name and the
-- picture to whoever needs to render them, and neither is needed on the server
-- for anything; the email is here because it is what links a purchase made at
-- checkout to an account that signs in afterwards, and nothing else.
CREATE TABLE IF NOT EXISTS academy_users (
  google_subject text PRIMARY KEY,
  email text NOT NULL,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  login_count integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS academy_users_email_idx ON academy_users (email);
CREATE INDEX IF NOT EXISTS academy_users_last_seen_idx ON academy_users (last_seen_at);

-- What a reader has finished, so it follows them off the device they started on.
--
-- The two array columns are sets, not sequences: `completePracticeItem` and
-- `viewLecture` on the client both check membership before appending, and the
-- merge on the way in does the same. Bounded on write, because they arrive from
-- a browser and `localStorage` is editable by whoever owns the browser.
CREATE TABLE IF NOT EXISTS learner_progress (
  google_subject text PRIMARY KEY REFERENCES academy_users (google_subject) ON DELETE CASCADE,
  resume_started boolean NOT NULL DEFAULT false,
  resume_completed boolean NOT NULL DEFAULT false,
  interview_started boolean NOT NULL DEFAULT false,
  interview_answers integer NOT NULL DEFAULT 0,
  interview_completed boolean NOT NULL DEFAULT false,
  practice_completed text[] NOT NULL DEFAULT '{}',
  lectures_viewed text[] NOT NULL DEFAULT '{}',
  last_tool text CHECK (last_tool IN ('resume', 'interview', 'practice')),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Sign-in attempts, kept long enough to answer "when did this start failing".
--
-- `user_hash` is the same HMAC `metrics.user_id()` puts on the Prometheus
-- label, so a spike on the dashboard and a row here name the same person
-- without either of them holding an email address. `google_subject` is only
-- present once an attempt has actually identified someone.
CREATE TABLE IF NOT EXISTS login_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  google_subject text,
  user_hash text,
  outcome text NOT NULL,
  country text,
  client text,
  retention_until timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS login_events_occurred_idx ON login_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS login_events_subject_idx ON login_events (google_subject);
CREATE INDEX IF NOT EXISTS login_events_retention_idx ON login_events (retention_until);

-- Server-proxied AI calls, one row each. Prompts, responses and keys are not
-- here for the same reason they are not Prometheus labels: nothing downstream
-- needs them, and keeping them would make this table the most sensitive thing
-- in the database. What is here is what a per-user quota or a usage history has
-- to be able to count.
CREATE TABLE IF NOT EXISTS ai_usage_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  google_subject text,
  user_hash text,
  provider text NOT NULL,
  model text NOT NULL,
  status integer NOT NULL,
  country text,
  client text,
  retention_until timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS ai_usage_events_occurred_idx ON ai_usage_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS ai_usage_events_subject_idx ON ai_usage_events (google_subject, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ai_usage_events_retention_idx ON ai_usage_events (retention_until);

-- Test history. The Pushgateway holds only the latest push per grouping key,
-- so "history" there is one run deep; this is the part that accumulates.
--
-- A rerun of the same GitHub run replaces its suites rather than adding to
-- them, which is what the unique key and the `ON CONFLICT` in `test_history.py`
-- are for — otherwise a re-run doubles every count.
CREATE TABLE IF NOT EXISTS test_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository text NOT NULL,
  branch text NOT NULL,
  commit_sha text NOT NULL,
  run_id text NOT NULL,
  run_attempt integer NOT NULL DEFAULT 1,
  completed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (repository, run_id, run_attempt)
);
CREATE INDEX IF NOT EXISTS test_runs_branch_completed_idx ON test_runs (branch, completed_at DESC);

CREATE TABLE IF NOT EXISTS test_suite_results (
  run_id bigint NOT NULL REFERENCES test_runs (id) ON DELETE CASCADE,
  suite text NOT NULL,
  passed integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0,
  broken integer NOT NULL DEFAULT 0,
  skipped integer NOT NULL DEFAULT 0,
  unknown integer NOT NULL DEFAULT 0,
  duration_seconds double precision NOT NULL DEFAULT 0,
  PRIMARY KEY (run_id, suite)
);

-- Nothing here is public, and `public` is the schema PostgREST serves.
--
-- Row level security with no policy is a closed door for every role that is not
-- the table's owner, and the owner is the role this API connects as. The
-- revoke is belt and braces: Supabase grants the two API roles broad access to
-- new tables in this schema by default, and a grant that was never made cannot
-- be the one that leaks.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'course_purchases', 'api_rate_limits', 'academy_users', 'learner_progress',
    'login_events', 'ai_usage_events', 'test_runs', 'test_suite_results'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM anon, authenticated;', t);
  END LOOP;
END $$;
